### ISSUE TITLE
Improved Integer Conversions

### ISSUE THREAD

**Issue by ds5678** [AssetRipper/TextureDecoder#19]
Assuming unsigned integers (because conversion from signed is lossless), the proper conversion calculations should be:

#### 4-bit to 8-bit

```cs
byte converted = original * 17;
```

#### 8-bit to 16-bit

```cs
ushort converted = original * 257; //or (original << 8) | original
```

#### 8-bit to 4-bit

```cs
var converted = (original * 15 + 135) >> 8; //Supposedly
```

#### 16-bit to 8-bit

```cs
byte converted = (original * 255 + 32895) >> 16; //Supposedly
```

However, I don't trust any of the formulas except 4 to 8 and 8 to 16. The others will have to be verified as accurate. We should also check for improvements to 5 and 6 bit color conversions.

References:
* https://stackoverflow.com/questions/2442576/how-does-one-convert-16-bit-rgb565-to-24-bit-rgb888
* http://threadlocalmutex.com/?p=48
* http://threadlocalmutex.com/?page_id=60

**Comment by NotOfficer** [comment]
16 to 8 should be accurate, the same code is used in the UnrealEngine:
```cpp
static uint8 Requantize16to8(int Value16)
{
	check( Value16 >= 0 && Value16 <= 65535 );

	// Dequantize x from 16 bit (Value16/65535.f)
	// then requantize to 8 bit with rounding (GPU convention UNorm)

	// matches exactly with :
	//  (int)( (Value16/65535.f) * 255.f + 0.5f );
	int Value8 = (Value16*255 + 32895)>>16;
	return (uint8)Value8;
}
```
